# Script mode only (cmake -P). Converts one binary file into a C++ TU that
# defines <NAMESPACE>::<SYMBOL>() returning an ember Span over the bytes.
# Generic on purpose: SYMBOL is the full accessor name, so the same script
# serves shaders today and any other embedded blob later.
#
# Required: -DINPUT= -DOUTPUT= -DSYMBOL= -DNAMESPACE= -DHEADER=

cmake_minimum_required(VERSION 3.20)

foreach(arg IN ITEMS INPUT OUTPUT SYMBOL NAMESPACE HEADER)
	if(NOT DEFINED ${arg})
		message(FATAL_ERROR "EmbedBlob.cmake: missing -D${arg}=")
	endif()
endforeach()

if(NOT EXISTS "${INPUT}")
	message(FATAL_ERROR "EmbedBlob.cmake: input does not exist: ${INPUT}")
endif()

file(READ "${INPUT}" hex HEX)

if(hex STREQUAL "")
	message(FATAL_ERROR "EmbedBlob.cmake: input is empty: ${INPUT}")
endif()

string(TOUPPER "${SYMBOL}" symbol_upper)
cmake_path(GET INPUT FILENAME input_name)

# Hex pairs to byte literals, wrapped every 16 bytes to keep the TU sane.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," bytes "${hex}")
string(REGEX REPLACE "((0x[0-9a-f][0-9a-f],){16})" "\\1\n\t\t\t" bytes "${bytes}")

string(CONCAT content
	"// Generated by EmbedBlob.cmake from ${input_name}. Do not edit.\n"
	"#include <${HEADER}>\n"
	"\n"
	"namespace ${NAMESPACE}\n"
	"{\n"
	"\tnamespace\n"
	"\t{\n"
	"\t\t// SPIR-V is a u32 stream; the alignment is load-bearing.\n"
	"\t\talignas(4) constexpr unsigned char ${symbol_upper}_DATA[] = {\n"
	"\t\t\t${bytes}\n"
	"\t\t};\n"
	"\t}\n"
	"\n"
	"\tember::Span<const ember::u8> ${SYMBOL}() noexcept\n"
	"\t{\n"
	"\t\treturn {${symbol_upper}_DATA, sizeof(${symbol_upper}_DATA)};\n"
	"\t}\n"
	"}\n"
)

file(WRITE "${OUTPUT}" "${content}")
